name: Lint & Format

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install black ruff

      - name: Format check (black)
        run: black --check .

      - name: Lint (ruff)
        run: ruff check .
